### PR TITLE
Plugin for PyPI api tokens

### PR DESCRIPTION
**Pull request by Chandra158**
## Please check if the PR fulfills these requirements
- [x] Tests for the changes have been added

- [x] Docs have been added / updated

- [x] All CI checks are green

## What kind of change does this PR introduce?

- Feature: new plugin for PyPI tokens
- [Token format](https://warehouse.pypa.io/development/token-scanning.html): 
> PyPI token is bound to start with:
> pypi-AgEIcHlwaS5vcmc[A-Za-z0-9-_]{70,}
> A token can be arbitrary long because we may add arbitrary many caveats.

## Tests
- New test added for plugin

### CODE REVIEW

**Review by lorenzodb1 — COMMENTED** [review]
Two questions:
1) does the TestPypi token have the same format?
2) is there a way to check the validity of the token?

**Comment by Chandra158** [comment]
> 1. does the TestPypi token have the same format?

TestPypi has different format: `pypi-AgENdGVzdC5weXBpLm9yZw[A-Za-z0-9-_]{70,}`

> 2. is there a way to check the validity of the token?

This is not supported yet. ([refs](https://github.com/pypi/warehouse/issues/6407))
There're some hacky way to do it but it'd also require other details like `username` in addition to the token.

**Comment by lorenzodb1** [comment]
Could you add checks for Test Pypi too?

>There're some hacky way to do it but it'd also require other details like `username` in addition to the token.

Do you think is something we could add as optional? Maybe you could add it as a configurable option for the user in the baseline file.

**Comment by Chandra158** [comment]
Added a new commit for the test.pypi tokens. 

> Do you think is something we could add as optional? 

IMO, there's no way to validate yet.

**Review by lorenzodb1 — APPROVED** [review]

**Pull request merged**
