### PR TITLE
Add initial Dockerfile

### PR DESCRIPTION
**Pull request by gliptak**
Signed-off-by: Gábor Lipták <gliptak@gmail.com>

```
docker run detect-secrets:latest
usage: detect-secrets [-h] [-v] [--version] {scan,audit} ...

positional arguments:
  {scan,audit}

optional arguments:
  -h, --help     show this help message and exit
  -v, --verbose  Verbose mode.
  --version      Display version information.
```

### CODE REVIEW

**Comment by gliptak** [comment]
@KevinHock @0atman @Yelp please review

**Comment by 0atman** [comment]
Not sure why I'm tagged (and given the thread bump you're trying to do, I'm not sure I appreciate it) but I sure do love Docker! :smile: 

There must be more to this docker method outside this PR, how are the files to be scanned shared in to the container?

Your example of `docker run detect-secrets:latest` won't find **any** project files (unless python:3-slim does something very surprising that I'm unaware of).

You might try something like `docker run -v $(pwd -P):/code/ [...]`.

Please provide adequate testing information.

**Comment by gliptak** [comment]
When the ```Dockerfile``` is committed, I will follow with a README update like:

https://github.com/aws-cloudformation/cfn-python-lint/pull/1397/files

PS I tagged you as you recently committed to this repo

**Comment by 0atman** [comment]
Why not add the readme to this PR?

I'm not sure how @yelp do things, but where I come from, PRs are atomic,
and have all the information needed to test 👌

**Comment by gliptak** [comment]
@0atman as the title says, this is an initial version of the Dockerfile and testing information was provided in the first comment.

**Pull request closed without merging**
