### PR TITLE
Added Verifiability Slack

### LINKED ISSUE #232: Add verifiability for Slack webhooks
As @dgzlopes helpfully linked to, https://github.com/streaak/keyhacks#slack-webhook shows how we can add this. 

See #194 for an example of how we do this in detect-secrets, e.g. we already have validation for Slack tokens https://github.com/Yelp/detect-secrets/blob/cba044666f1d8a9c8cd2e428fd4f90376d50bf1c/detect_secrets/plugins/slack.py#L30-L39

The parent issue (#153) is [still opened](https://github.com/Yelp/detect-secrets/issues/153#issuecomment-504284806) but figured I'd make this as a `good first issue`.

### PR DESCRIPTION
**Pull request by Patil2099**
Fixes #232

### CODE REVIEW

**Comment by Patil2099** [comment]
@KevinHock the test is still failing

**Comment by KevinHock** [comment]
We’re you able to run the hooks? It seems they are still modifying files.

**Comment by Patil2099** [comment]
@KevinHock Sorry I was not able to run the hook.

**Comment by KevinHock** [comment]
No worries @Patil2099 

@OiCMudkips can you merge this when you get a chance and run the hooks right after? Alternatively, I can do it once I'm back.

**Pull request merged**
