### PR TITLE
Multiple filters support and secret filter by regex

### PR DESCRIPTION
**Pull request by pablosantiagolopez**
This Pull Request includes the following features:

- Support for multiple filters: it allows multiple occurrences of the CLI options `--exclude-lines` and `--exclude-files`. The user can apply multiple regexes to filter the output of detect-secrets.
- New `secret` filter by regex: it could be interesting to discard fake secrets of secrets that are external references to, for example, environmental variables.

The `tests/filters/regex_filter_test.py` has been updated to the multiple regexes support and includes the `test_should_exclude_secret` that tests the new secret filter.

### CODE REVIEW

**Comment by pablosantiagolopez** [comment]
Hello @domanchi, this pull request resolves the problem described in #403. This feature could improve the usability and the configuration of the detect-secrets tool.

**Review by domanchi — COMMENTED** [review]
Great work! A couple of things to add, before we can merge this:

- Be sure to document this in the [filters documentation](https://github.com/Yelp/detect-secrets/blob/pre-v1-launch/docs/filters.md#built-in-filters)
- As this adds a new flag, be sure to also update the README ([here](https://github.com/Yelp/detect-secrets/tree/pre-v1-launch#adding-secrets-to-baseline), and [here](https://github.com/Yelp/detect-secrets/tree/pre-v1-launch#filters))
- Since this modifies the baseline, you also need to [modify the upgrade script](https://github.com/Yelp/detect-secrets/blob/pre-v1-launch/detect_secrets/core/upgrades/v1_0.py#L57-L70) to ensure backwards compatibility

**Comment by pablosantiagolopez** [comment]
Thank you for your detailed comment, I think that everything is updated

**Review by domanchi — APPROVED** [review]

**Comment by domanchi** [comment]
I have verified that all tests pass with this branch.

**Pull request merged**
