### PR TITLE
Avoid IndexError when passing an empty string to `is_prefixed_with_dollar_sign`

### PR DESCRIPTION
**Pull request by sindrig**
- [x] Tests for the changes have been added

- [ ] Docs have been added / updated

- [x] All CI checks are green

* **What kind of change does this PR introduce?**

As shown by the test, we want to return False for the empty string when checking if it is prefixed with a dollar.

* **What is the current behavior?**

The function `is_prefixed_with_dollar_sign` raises `IndexError` when called with the empty string.

* **What is the new behavior (if this is a feature change)?**

`is_prefixed_with_dollar_sign` returns False for the empty string.

### CODE REVIEW

**Comment by lorenzodb1** [comment]
@sindrig thank you for your contribution 😄 could you please merge master into your branch?

**Comment by sindrig** [comment]
> @sindrig thank you for your contribution 😄 could you please merge master into your branch?

Done :heavy_check_mark:

**Comment by sindrig** [comment]
> @sindrig thank you for that! Looks like one of the pre-commit checks is failing. Please, run `make test` and then push the changes

Import order got mixed up. Fixed :white_check_mark:

**Review by lorenzodb1 — APPROVED** [review]

**Comment by lorenzodb1** [comment]
@sindrig Thank you for your contribution! I went ahead and merged your changes. Really appreciate your work and hope to see another PR of yours soon 😄

**Pull request merged**
