### PR TITLE
Not every company has a #security channel in slack/irc

### PR DESCRIPTION
**Pull request by 0atman**
> For information about putting your secrets in a safer place, please ask in #security

For us, in @alphagov, our **#security** channel is for physical security questions and our cyber security team hang out in **#cybersecurity**.

This seems like the simplest way to get the message changed, working even for people who don't - or can't - use a config.

My edits formatted with [black](https://github.com/psf/black)
EDIT: They're now linted by flake8, in accordance with the CI.

### CODE REVIEW

**Comment by 0atman** [comment]
Thanks @KevinHock! What a treat. Is there anything else I can help with in regard to getting this into the next release?

**Comment by KevinHock** [comment]
No, thank you though 👍

It’ll automatically be in the next release, maybe the week after next.

**Comment by 0atman** [comment]
Brilliant! What a pleasure, thank you.

**Comment by KevinHock** [comment]
Hi @0atman, just wanted to let you know that there was a new release, `v13.0.1` https://github.com/Yelp/detect-secrets/blob/master/CHANGELOG.md#v0131, with your changes in it.

Cheers,
-Kevin

**Comment by 0atman** [comment]
Thank you so much! It works for me, I'll roll it out to our install :ok_hand:

**Pull request merged**
